name: Nuget

on:
  push:
    tags:
      - 1.*

jobs:
  Nuget:
    # use ubuntu-latest image to run steps on
    runs-on: ubuntu-latest
    steps:
    # uses GitHub's checkout action to checkout code form the master branch
    - uses: actions/checkout@v2
    
    # sets up .NET Core SDK 3.1
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1.9.0
      with:
        dotnet-version: 6.0.101
            
    - name: Set Variables
      id: branch_name
      run: |
        echo ::set-output name=SOURCE_NAME::${GITHUB_REF#refs/*/}
        echo ::set-output name=SOURCE_BRANCH::${GITHUB_REF#refs/heads/}
        echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}
        
    - name: Show Release Version
      run: |        
        echo ${{ steps.branch_name.outputs.SOURCE_NAME }}
        echo ${{ steps.branch_name.outputs.SOURCE_BRANCH }}
        echo ${{ steps.branch_name.outputs.SOURCE_TAG }}

    # Build the project
    - name: Build Project
      run: dotnet build ./Hierarchy/Hierarchy.csproj -c Release
    
    - name: Pack for nuget
      if: contains(${{ env.RELEASE_VERSION }},'.')
      run: dotnet pack ./Hierarchy/Hierarchy.csproj -c Release -p:PackageVersion=${{ steps.branch_name.outputs.SOURCE_TAG }}

    - name: Push to nuget
      if: contains(${{ env.RELEASE_VERSION }},'.')
      run: dotnet nuget push ./Hierarchy/bin/Release/Hierarchy.${{ steps.branch_name.outputs.SOURCE_TAG }}.nupkg --skip-duplicate --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
